# Generated by Django 3.1.4 on 2020-12-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0004_auto_20201218_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sale_offer', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
