# Generated by Django 3.1.4 on 2020-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0005_headbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='headbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
    ]
